name: pages

on:
  push:
    branches:
      - trunk

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pages:
    runs-on: atlas-nix-trusted
    steps:
      - uses: actions/checkout@v4
      - name: Build site
        run: nix build .#site
      - name: Deploy to Codeberg Pages
        env:
          GIT_AUTHOR_NAME: forgejo-actions
          GIT_AUTHOR_EMAIL: forgejo-actions@noreply.codeberg.org
          DEPLOY_REMOTE: pages-origin
        run: |
          git remote add pages-origin https://codeberg.org/caniko/$proj
          nix run .#deploy-pages
