[package]
name = "sorrel"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "sorrel"
path = "src/main.rs"

[dependencies]
sorrel-io.workspace = true
sorrel-cache.workspace = true
sorrel-data.workspace = true
sorrel-render.workspace = true
sorrel-ui.workspace = true
eframe.workspace = true
egui.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true

[features]
default = []
hdf5 = ["sorrel-io/hdf5", "sorrel-data/hdf5"]

[dev-dependencies]
tempfile.workspace = true
