[package]
name = "sorrel-render"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Concrete vertices and GPU buffer builders for Sorrel rendering."

[dependencies]
sorrel-io.workspace = true
sorrel-data.workspace = true
sorrel-compute.workspace = true
sorrel-gpu.workspace = true
bytemuck.workspace = true
log.workspace = true

[dev-dependencies]
tempfile.workspace = true
