base_url = "https://caniko.codeberg.page/sorrel"
title = "Sorrel"
description = "Native, high-performance GUI for manual curation of spike-sorted electrophysiology data."
default_language = "en"

compile_sass = true
build_search_index = false
minify_html = false
generate_feeds = false
hard_link_static = true

[markdown]
[markdown.highlighting]
theme = "nord"
