[book]
title = "Sorrel Documentation"
authors = ["caniko"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
site-url = "/docs/"
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://codeberg.org/caniko/sorrel"
